services:
  database:
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    environment:
      - DB_SOURCE=postgresql://user:password@localhost:port/db?sslmode=disable
    volumes:
      - /C/Users/UnT3a/Music:/app/music

volumes:
  pgdata: