services:
  database:
    container_name: db
    image: postgres:16-alpine3.19
    ports:
      - "5432:5432"
    restart: always

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    depends_on:
      - database
    command: ["/app/migration.sh"]