services:
  database:
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=flacster
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    environment:
      - DB_SOURCE=postgresql://admin:1234@database:5432/flacster?sslmode=disable
    volumes:
      - /C/Users/UnT3a/Music:/app/music

volumes:
  pgdata: